language: generic
sudo: required

services:
  - docker

branches:
  only:
    - master

script:
  - cd setup
  - ./docker_build.py
  - ./docker_run.py --entrypoint="mkdir build && cd build && cmake .. && make"
